[package]
name = "starrynift_nft_box"
version = "0.0.0"
#published-at = ""

[dependencies]
# mainnet
#Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "ae1212baf8f0837e25926d941db3d26a61c1bea2" }
#NftProtocol = { git = "https://github.com/Origin-Byte/nft-protocol.git", subdir = "contracts/nft_protocol", rev = "develop" }

# testnet
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "e4fe9f5ed5e240a718571f23bc75e12e60445288" }
NftProtocol = { git = "https://github.com/Origin-Byte/nft-protocol.git", subdir = "contracts/nft_protocol", rev = "to-merge-to-main" }

[addresses]
starrynift_nft_box = "0x0"
